---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://Braytonio.github.io/project-miserables"
title: "Confessions of a Paraguayan Marlboro Man"
canonifyurls: true
theme: "ghostwriter"
...
